services:  
  dont_email_passwords:
    image: ghcr.io/necrolingus/dont_email_passwords:latest
    restart: unless-stopped
    env_file: 
     - .env
    expose:
      - 3002
    networks:
      - internal_proxy

networks:
  internal_proxy:
    external: true